//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string CABEZA = "cabeza";
        
        public const string TORSO = "torso";
        
        public const string TORSODELANTE = "torsodelante";
        
        public const string TORSODETRAS = "torsodetras";
        
        public const string LEFT_HAND_WARNING = "left_hand_warning";
        
        public const string RIGHT_HAND_WARNING = "right_hand_warning";
    }
}
